### ISSUE TITLE
 Is it possible to have a 0.9.0 version ? apiguardian-api : 1.0.0 -. 1.1.0

### ISSUE THREAD

**Issue by mikrethor** [zalando/faux-pas#167]
There are some conflict with apiguardian-api in some projects. Indeed the 0.8.0 version contains apiguardian-api 1.0.0 and the project problem-spring-web use that version and brings apiguardian-api 1.1.0 so the versions are not consistent with the one in the 0.8.0 of faux-pas (1.0.0).

**Comment by whiskeysierra** [comment]
Sorry, I missed this somehow. What changed with API Guardian? Is it a breaking change?

**Comment by whiskeysierra** [comment]
1.0.0 to 1.1.0 sounds like it should be backwards-compatible.

**Comment by whiskeysierra** [comment]
I released 0.9.0 just now. Thanks for raising this 📣
