### ISSUE TITLE
Consider adding support for more functional interface types

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/faux-pas#8]
**List of candidates** from [`java.util.function`](https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html)
- [x] BinaryOperator
- [x] BooleanSupplier
- [x] DoubleBinaryOperator
- [x] DoubleConsumer
- [x] DoubleFunction
- [x] DoublePredicate
- [x] DoubleSupplier
- [x] DoubleToIntFunction
- [x] DoubleToLongFunction
- [x] DoubleUnaryOperator
- [x] IntBinaryOperator
- [x] IntConsumer
- [x] IntFunction
- [x] IntPredicate
- [x] IntSupplier
- [x] IntToDoubleFunction
- [x] IntToLongFunction
- [x] IntUnaryOperator
- [x] LongBinaryOperator
- [x] LongConsumer
- [x] LongFunction
- [x] LongPredicate
- [x] LongSupplier
- [x] LongToDoubleFunction
- [x] LongToIntFunction
- [x] LongUnaryOperator
- [x] ObjDoubleConsumer
- [x] ObjIntConsumer
- [x] ObjLongConsumer
- [x] ToDoubleBiFunction
- [x] ToDoubleFunction
- [x] ToIntBiFunction
- [x] ToIntFunction
- [x] ToLongBiFunction
- [x] ToLongFunction
- [x] UnaryOperator

**Comment by jhorstmann** [comment]
Some form of code generation could be useful to implement all those consistently.

**Comment by whiskeysierra** [comment]
Indeed

**Comment by whiskeysierra** [comment]
I can't find it right now, but I remember Guava back in the day had a shell script that was used to *write* the primitive utility classes, i.e. `Ints` and `Longs`.

**Comment by whiskeysierra** [comment]
I also think we should choose the ones that are useful, not blindly use all of them. Thoughts?

**Comment by whiskeysierra** [comment]
I checked the ones that I never used until now, not even once. That only left two:

- [ ] BinaryOperator
- [ ] UnaryOperator

I'm going to add support for those.
