### ISSUE TITLE
This project seems to be heavily-inspired by throwing-function and doesn't comply with the license

### ISSUE THREAD

**Issue by pivovarit** [zalando/faux-pas#99]
#### This project seems to be heavily-inspired by [throwing-function](https://github.com/pivovarit/throwing-function) and doesn't comply with the original license.

`throwing-function` was released/published in February 2016, half a year before the first release of `faux-pas`

## Description

`faux-pas`:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/2182533/57965154-9c614900-7940-11e9-8b04-5ff577bd28f5.png">

`throwing-function`:

<img width="396" alt="image" src="https://user-images.githubusercontent.com/2182533/57965179-e77b5c00-7940-11e9-9f12-2d95e9a14f14.png">

This project seems to be heavily-inspired by [throwing-function](https://github.com/pivovarit/throwing-function) and doesn't comply with the license

## Expected Behavior
The `faux-pas` project should be compliant with the license and not be a _faux pas_.

## Actual Behavior
The `faux-pas` project is not compliant with the license and is a _faux pas_.

## Possible Fix
I can think of at least two solutions:
- delete the project
- do all the necessary steps to be compliant with https://github.com/pivovarit/throwing-function/blob/master/LICENSE

**Comment by perploug** [comment]
Hi @pivovarit 

Thanks for reaching out, we of course take your license compliance claim very seriously and are currently investigating this.

To make sure I understand this issue correctly - do you see Faux-Pas containing code copied from your project, or is it a matter of a similar API naming structure?

Looking into the source code history of Faux-Pas, it does not look like our developers have copied code from your project, but please point me to those areas, if I have overlooked anything. 

Looking at the identical API structures, this comes from prefixing core Java 8 interfaces with the word "Throwing" - searching through github there are several libraries who use this structure, and is thus a fairly common naming convention for a project of this type. 

If there is a case of breaching your license, we will ofcourse comply with its requirements

Also please feel free to reach out to me directly: per.ploug@zalando.de - in case the github notifications get lost in my inbox 

Per Ploug
Open Source Manager @ Zalando SE

**Comment by pivovarit** [comment]
Hi @perploug 

> Do you see Faux-Pas containing code copied from your project, or is it a matter of a similar API naming structure?

No, it's definitely not copied - most likely a coincidental naming clash. No worries - I'm not a threat - just wanted to make you aware :)

**Comment by perploug** [comment]
Hey @pivovarit - didn't intend to make it sound like you were being "handled" like a threat - so apologies for that :) 

Thanks for clarifying and the quick response 👍

**Comment by pivovarit** [comment]
No, it did not sound like this - just wanted to make sure that I didn't sound like this over traces of sarcasm in my initial post :)
